# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151205_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created'], 'verbose_name': '\u6587\u7ae0'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
