# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160222_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created'], 'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
